### PR TITLE
CHIEF - Added use of ARMORATTACK

### PR DESCRIPTION
**Pull request by Applevangelist**

### CODE REVIEW

**Comment by funkyfranky** [comment]
You could leave the line
`--table.insert(missionperf, self:_CreateMissionPerformance(AUFTRAG.Type.ARTY, 30))`
in. It would only fall back to that if other types have no assets available.

Also, I would say that an airstrike (CAS or BAI) should probably be preferred over a ground attack. In general and given DCS problems with routing on ground and ground assets not being able to go everywhere.

**Comment by Applevangelist** [comment]
Yeah right, higher mission performance is preferred right?

**Comment by funkyfranky** [comment]
> Yeah right, higher mission performance is preferred right?

yup

**Comment by Applevangelist** [comment]
ok, altered now

**Pull request merged**
