### PR TITLE
Update Controllable.lua

### PR DESCRIPTION
**Pull request by Applevangelist**
Add option to control a2a attack ranges for AIR fighter units. See https://wiki.hoggitworld.com/view/DCS_option_missileAttack

### CODE REVIEW

**Review by baluballa — APPROVED** [review]
Looks good to me, can't see any wrong or harmful with code. 

Wonder you guys not check for _valid input_ like 
```if range < 0 or range >= 5```
Have you tested inpact on performance if range is set to 6?

**Comment by Applevangelist** [comment]
You're right, we should add this check.

**Comment by Applevangelist** [comment]
Can you request changes, Wingthor, I'll add a check

**Comment by Applevangelist** [comment]
never mind, done

**Comment by baluballa** [comment]
Don't me wrong @Applevangelist, your code looks ok to me. @funkyfranky must do the final merge.

My comment was meant more generally. Documentation should be more than enough. Some "errors" might have not be shown in logs, like if range is 6 in this case, but still cause strange behavior in performance.

**Comment by Applevangelist** [comment]
No worries, it was a good addition to make it noob proof. :)

**Pull request merged**
