### PR TITLE
Update Detection.lua

### PR DESCRIPTION
**Pull request by TommyC81**
Code formatting. Fix minor typos, errors, and references in documentation.

### CODE REVIEW

**Comment by Applevangelist** [comment]
Sorry this seems to revert a couple of code changes

**Review by Applevangelist — CHANGES_REQUESTED** [review]
woule be good to change the docu only, and not revert previous code changes pleeeeease!

**Comment by TommyC81** [comment]
Ugh, I did fetch and merge the latest prior. Please reject, and I'll
check/redo as appropriate.

**Comment by TommyC81** [comment]
Just to double check; when you say code changes, are you referring to the code formatting? I skimmed through the diff on my phone, and can't locate any code changes except formatting. Functionality should be unaffected. I'll have to check again once back at my computer though.

**Comment by TommyC81** [comment]
I've manually gone through the changes, and am a bit at a loss. There should be no code changes per se, albeit formatting updates (I've manually amended some tables in commits that have been force-pushed into this PR). Specifically, the recent updates in commit https://github.com/FlightControl-Master/MOOSE/commit/7bfa05f47d3bd67a9f85f69bab5dccddc455d332 are untouched (except for code formatting, mostly white spaces).

**Review by Applevangelist — APPROVED** [review]

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
