### PR TITLE
Feature/zone unit offsets

### PR DESCRIPTION
**Pull request by ezietsman**

### CODE REVIEW

**Comment by ezietsman** [comment]
Link to demo mission for this feature.
[https://www.dropbox.com/sh/ud2vb7hnbn7g2z1/AADiwBZjJmoWg2r-6IEFAqZVa?dl=0](url)

**Comment by Delta-99** [comment]
@ezietsman might be a good idea to your demo mission to the official demo mission repository. Would be worthwhile I would think. Up to you though.

**Comment by ezietsman** [comment]
@Delta-99 Sure thing. I read somewhere that the Moose.lua include is automatically injected into those missions. Is this correct?

**Comment by thebgpikester** [comment]
yep! Pretty amazing, some appVeyor tool, I dunno the details.

**Comment by ezietsman** [comment]
So I can just add my mission.lua and any moose.lua and send a PR?

**Comment by FlightControl-User** [comment]
@ezietsman your code is conflicting with other code in moose...

I understand why you have added the offset 

```
-- @return #ZONE_UNIT self
function ZONE_UNIT:New( ZoneName, ZoneUNIT, Radius, Offset)
```

But what if Offset is nil??? that is ... Not given as a paramter?
ZONE_UNIT is used in many places. So we would not update the existing code everywhere.
The solution I think is to make Offset optional.
So, I will add code to check if Offset is provided.
If not, all Offset stuff will be ignored.

**Comment by FlightControl-User** [comment]
I have fixed it with commit https://github.com/FlightControl-Master/MOOSE/commit/6b04237a3fc8186be6322f713cf84e085a4001b6 .

**Pull request merged**
