### PR TITLE
Update Modules.lua and Moose.files

### PR DESCRIPTION
**Pull request by TommyC81**
Update Modules.lua to reflect actual filenames, missing files commented out (i.e. ZoneGoalCargo.lua, AI_Air_Squadron.lua, and AI_Air_Dispatcher.lua).

Update Moose.files to be identical to Modules.lua (without the commented out files).

### CODE REVIEW

**Comment by Applevangelist** [comment]
Need to muse this. Not sure it breaks the build workflow

**Comment by TommyC81** [comment]
For sure, no stress! The most interesting thing I noticed is that not all files in the repository are included in the Modules.lua, maybe that's intentional? I'm not sufficiently familiar with the code to tell. At least it's good confirmation of the status of the files vs the code base.

**Comment by Applevangelist** [comment]
> For sure, no stress! The most interesting thing I noticed is that not all files in the repository are included in the Modules.lua, maybe that's intentional? I'm not sufficiently familiar with the code to tell. At least it's good confirmation of the status of the files vs the code base.

Yes, that's intentional

**Comment by Applevangelist** [comment]
I think we have determined to go another route

**Pull request closed without merging**
