### PR TITLE
Added Hermes section to Airboss.  Will require tuning.

### PR DESCRIPTION
**Pull request by gavinedwards**
I've added a section to include Hermes mods to work with Airboss.

### CODE REVIEW

**Comment by funkyfranky** [comment]
Great stuff. Thanks for the addition.

Very small thing. I noticed the first two lines of the Airboss.lua are remove, i.e.
```
--- **Ops** - Manages aircraft CASE X recoveries for carrier operations (X=I, II, III).
--
```
Can you re-add them. Because otherwise, the autogenerated docs will not look correctly.

**Comment by gavinedwards** [comment]
> Great stuff. Thanks for the addition.
> 
> Very small thing. I noticed the first two lines of the Airboss.lua are remove, i.e.
> 
> ```
> --- **Ops** - Manages aircraft CASE X recoveries for carrier operations (X=I, II, III).
> --
> ```
> 
> Can you re-add them. Because otherwise, the autogenerated docs will not look correctly.

Absolutely, not sure why they truncated, will fix.

**Comment by gavinedwards** [comment]
@funkyfranky, should be added now.

**Review by funkyfranky — APPROVED** [review]

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
