### PR TITLE
Update Task_A2A_Dispatcher.lua

### PR DESCRIPTION
**Pull request by Applevangelist**
Add boolean in new to suppress "... has new tasks..." flashes

### CODE REVIEW

**Review by baluballa — APPROVED** [review]

**Comment by Applevangelist** [comment]
thanks

**Comment by funkyfranky** [comment]
This was not committed, right?

**Comment by baluballa** [comment]
I have not committed anything. Just approved, as far as I know...

**Comment by baluballa** [comment]
Or merged/pulled if that is what you mean? I guess @Applevangelist has committed in his repository.

**Comment by funkyfranky** [comment]
Yes, I meant merged. Looks like you approved and @Applevangelist just closed it. I'll reopen.

**Pull request merged**
