### PR TITLE
Make default cargo bay capacity values configurable

### PR DESCRIPTION
**Pull request by ttrebuchon**
Resolves: #1988  (Potential implementation)

### CODE REVIEW

**Comment by Applevangelist** [comment]
Good idea. I think this has a semicolon too many and should be part of the class, not stand alone:  `local _DefaultInfantryWeight = 95;`

**Comment by ttrebuchon** [comment]
Whoops, yeah the semicolon is my C++/C# habits popping in, I'll take that out.

My concern with moving the infantry weight variable into the class is that making it changeable wouldn't change anything, as the weights for the ground vehicles would still only be calculated once. If we really wanted to make it customizable, I could move the `X*DefaultInfantryWeight` calculation back into the code as it was before, but then the table itself is inconsistent because the Air and Naval options would be in kg, but Ground would be in infantry-count instead.

The reason I made it a separate variable, rather than moving a hard coded *95 into the table declaration was more to leave the "why those values" were picked and the comments intact. (and also so that if it turns out that 95 isn't enough, it's trivially changeable).

With my reasoning given, let me know if I should still move it into the class or not and I'll get on that!

**Comment by ttrebuchon** [comment]
Ah. I also just realized that the way I currently have it set up, the table would be copied as part of the BASE:Inherit in the constructor, rather than staying as a sort of static member. Maybe the `POSITIONABLE.SetDefaultTypeCargoCapacity("Air"/"Naval"/"Ground", "XYZ", ###)` implementation would be better after all?

I could move the actual table itself to POSITIONABLE._ instead which I believe would keep it from being copied to instantiated POSITIONABLEs, if I'm correct? I'll verify for certain when I get to my workstation this morning

**Comment by Applevangelist** [comment]
Systematically it makes more sense to move this table to ENUMS, so like ENUMS.CargoCapacity… then the default base soldier’s weight can be another entry like ENUMS.DefaultSoldierWeight etc

**Comment by ttrebuchon** [comment]
1) I did verify for certain that the table would be duplicated across all instances of POSITIONABLE if we stored it on there, regardless of where we put it. (Sidenote: the entire AIRBASE.Caucasus / AIRBASE.PersianGulf / etc tables are being copied to every airbase too, but probably not as big of a performance impact unless there are quite a few carriers/ships with helo pads being utilized)

2) I agree that something like ENUMS would be a better place to put it even though it's not exactly a traditional enum, since it's intended for user modification and extension. Ideally there would be some sort of singleton CONFIG class or CONSTANTS class or something that it could be stored in.

I don't suppose this would be a candidate for adding it to DATABASE, would it? Closest sort of thing to a singleton, modifiable value-store that I can see.

I'm going to open up another PR with an alternative implementation option that might avoid some of the issues with this one.

**Pull request merged**
