### PR TITLE
Update Airboss.lua

### PR DESCRIPTION
**Pull request by TommyC81**
Primarily code formatting. Some minor typo fixing.

This contains a massive number of changes due to the sheer size of the file...

### CODE REVIEW

**Comment by TommyC81** [comment]
Pushed/Forced two additional commits as I manually corrected some formatting changes for readability. Squashed.

**Review by Applevangelist — APPROVED** [review]

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
