### PR TITLE
Pene lha and lhd edits

### PR DESCRIPTION
**Pull request by Penecruz**
- Changes to add voice over to spot 5 on the Juan Carlos L61.
- Additional video and instructions for Av-8B pattern.

### CODE REVIEW

**Comment by Penecruz** [comment]
Hi Guys, I have additional voice over files for spot 5 both in LSO FF and Raynor to be included in the Airboss sound files and Raynor voice pack.

[Airboss Soundpack spot 5 additions.zip](https://github.com/FlightControl-Master/MOOSE/files/7070157/Airboss.Soundpack.spot.5.additions.zip)

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
