### PR TITLE
AWACS - Tweaked Escort logic

### PR DESCRIPTION
**Pull request by Apollonaut-dev**
- Uses one AUFTRAG per escort fighter
- Each new escort fighter will slot into a wedge formation
-- Each escort 100 m outboard from the last
-- Each pair of escorts 100 m aft from the last
- More control over escorts will support future PR

### CODE REVIEW

**Comment by Apollonaut-dev** [comment]
I apologize for the diffs. Not sure what happened. I had to copy the changes from an off-git backup because I screwed up squashing multiple commits, lol.

**Review by Applevangelist — APPROVED** [review]

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
