### PR TITLE
ATIS: Disable subtitles #1276

### PR DESCRIPTION
**Pull request by 132nd-Entropy**
ATIS:SetSubtitleDuration(0) now  disables the subtitles.

### CODE REVIEW

**Comment by funkyfranky** [comment]
Well, while this would work, it would be a lot easier to do the change in the Core RADIOQUEUE class. That would require only one general change. Let me try this first...

**Comment by 132nd-Entropy** [comment]
Yes ofc, im learning as I go 😊

**Comment by 132nd-Entropy** [comment]
I looked at CORE /Radio.lua but I could not figure out how to disable the subtitles. :(

**Comment by funkyfranky** [comment]
Because it is in the RadioQueue.lua ;)

**Pull request closed without merging**
