### PR TITLE
RANGE class

### PR DESCRIPTION
**Pull request by funkyfranky**
Added RANGE clase

### CODE REVIEW

**Comment by FlightControl-User** [comment]
One last comment.
When you have merged, you will need to put an alert to the users that those people who are dynamically loading moose, will **also** need to replace their Moose.lua. Because of the extra added Range.lua file.

**Comment by funkyfranky** [comment]
Okay, merged. Where is the best place for telling everyone to update the dynamic moose.lua?

**Comment by FlightControl-User** [comment]
Heum... maybe in announcement? You have access?

**Comment by funkyfranky** [comment]
No, I don't have access. Can you do it?

**Pull request merged**
