### PR TITLE
RAT error reports

### PR DESCRIPTION
**Pull request by 132nd-etcher**
- allows for switching in-game RAT errors reports on or off
- re-factored usage of MESSAGE throughout RAT (I found a few "rat.debug", switch to "self"); all messages are now conditional on either "debug" or "error"

### CODE REVIEW

**Comment by 132nd-etcher** [comment]
My previous comment is wrong; the in game messages are dependent on debug, reportstatus and a newly introduced reporterrors variable, with an added switch method.

I also removed a few if statements in favour of MESSAGE:ToAllIf

**Comment by FlightControl-Master** [comment]
@132nd-etcher @funkyfranky i am going to reject this one. I had to do a lot of updates on the previous commit. Please check together if my changes of the other pull request were done to deal with the conflicts! and please communicate :-)

**Comment by 132nd-etcher** [comment]
Updated fork

**Comment by FlightControl-Master** [comment]
@funkyfranky can you press the merge button after your review? @132nd-etcher has done some changes and i did some merging of changes suggested by etcher etc....

**Pull request closed without merging**
