### PR TITLE
Dcs luadoc to separate repo

### PR DESCRIPTION
**Pull request by birgersp**
#147 Moved the contents of `Moose Development/Dcs' to a separate repository, and added the repository as a submodule to MOOSE

### CODE REVIEW

**Comment by FlightControl-Master** [comment]
Hi, I think that is a good idea! Sorry for the very late reply. I've been very sick the past months, receiving a very harsh medical treatment. Now i am getting better again. Yes, you can copy the repository, as long as we both ensure that the prototypes can be kept in sync. Note that the prototypes are not completed yet.
How would you suggest to keep both in sync?

**Comment by birgersp** [comment]
Sorry to hear you've been sick, it's good to hear you're getting better! I'm sure the whole community will be glad to know if you're back to developing MOOSE :)

The MOOSE repository will track a specific commit of the submodule (luadoc repo). Whenever you want MOOSE to use the latest version of the submodule, you can run `git submodule update --remote` and commit to specify that MOOSE should now use the updated version of the submodule repo.

Submodules can take a little time to get used to, if you haven't already. Most noteably perhaps: the repo added as a submodule is *not* automatically synced (there's a very good reason for that).

If you want, I can transfer the luadoc repo to you and re-do this pull request so the submodule is referenced to you. Or I can just add you as admin to the dcs-sse-luadoc repo.

Btw, feel free to send me a PM on the [ED forums](https://forums.eagle.ru/member.php?u=114197) if you want

**Comment by FlightControl-Master** [comment]
Birger, can we get back to this item? Why is there a pull request?

**Comment by birgersp** [comment]
Certainly! Pull requests are simply a way for you (as the maintainer/administrator of the repository) to decide if you want to actually add the changes I did.

The way it works is that anyone who wants to do some work on your code must **request** the changes to be **pulled** into the projects codebase. The reason for a pull request is so that the maintainer can look over the changes and decide if they are good enough to be implemented. So now that I've made the pull request, you must decide if you want to accept it (merge it) or not :-)

[This tutorial](https://yangsu.github.io/pull-request-tutorial/) explains how to use pull requests in Github very well.

**Comment by FlightControl-Master** [comment]
I see your changes. You basically delete all and replace by a module, right?

Isn't it possible to keep the master of this in moose?

There ate two reasons for that:

1. The function prototypes haven't finished and is evolving.
2. It would be a good publicity.

I remember myself late hours working making ask this stuff. Want to keep the link...

Would like to add you as a contributor in moose.

Sv.

**Pull request merged**
