### PR TITLE
#CSAR - Add Persistence

### PR DESCRIPTION
**Pull request by TheChosenOn3**
* Adds a modified version of ops.CTLD's Persistence to ops.CSAR

### CODE REVIEW

**Comment by TheChosenOn3** [comment]
Test Mission, dynamic load (Note: Please create save path for CSAR script at **"C:\\MoosePersistence\\"**):
[CSAR Persistence Test.zip](https://github.com/FlightControl-Master/MOOSE/files/10512837/CSAR.Persistence.Test.zip)

**Comment by TheChosenOn3** [comment]
Video of Test Mission:
https://youtu.be/2yXVf5iTZqU

**Review by Applevangelist — APPROVED** [review]

**Comment by Applevangelist** [comment]
Thanks!

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Review by Applevangelist — COMMENTED** [review]
Checking C:\projects\Moose_Include\Moose_Include_Static\Moose_.lua OK  Total: 0 warnings / 0 errors in 1 file

**Pull request merged**
